name: Release Binary

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build and Release
    runs-on:
      group: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'
          cache: true

      - name: Build
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 1
        run: |
          # Create dist directory
          mkdir -p dist
          
          # Build the binary
          go build -v -o "dist/${GITHUB_REPOSITORY##*/}" -ldflags "-X main.Version=${GITHUB_REF_NAME}"

      - name: Generate SHA-256 Checksum
        run: |
          cd dist
          sha256sum * > sha256sums.txt

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}